DROP TABLE IF EXISTS user; 
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS seller; 
DROP TABLE IF EXISTS product_sizes; 
DROP TABLE IF EXISTS product_types; 

CREATE TABLE seller(
seller_id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT,
first_name TEXT,
last_name TEXT,
rating INTEGER,
registration_date INTEGER
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE product_types(
type_id INTEGER PRIMARY KEY AUTOINCREMENT,
description TEXT,
product_id INTEGER
);

CREATE TABLE product_sizes(
size_id INTEGER PRIMARY KEY AUTOINCREMENT,
product_id INTEGER NOT NULL,
size TEXT NOT NULL,
items_count INT NOT NULL
);

CREATE TABLE products (
product_id INTEGER PRIMARY KEY AUTOINCREMENT,
seller_id INTEGER NOT NULL,
title TEXT NOT NULL,
price INTEGER NOT NULL,
type INTEGER NOT NULL,
size INTEGER NOT NULL,
rating INTEGER NOT NULL,
rating_count INTEGER NOT NULL
);
